### ISSUE TITLE
Typo in Geometry - Write Geometry to JSON example

### ISSUE THREAD

**Issue by fsteggink** [pcjericks/py-gdalogr-cookbook#152]
Hi, there is a typo in the second example here: http://pcjericks.github.io/py-gdalogr-cookbook/geometry.html#write-geometry-to-geojson

The method ExportToJSON should be written as ExportToJson

Thanks for the cookbook. I just discovered it today, but it's already very useful to me.

**Comment by pcjericks** [comment]
Thanks for the bug report!

Jared
