### ISSUE TITLE
Missing documentation on memory driver

### ISSUE THREAD

**Issue by RolandLoewe** [pcjericks/py-gdalogr-cookbook#157]
The memory driver is very useful but extremely poorly documented. After some fiddling, the following works for me and I suggest adding something in this style to the cookbook:

#open an input datasource
indriver=ogr.GetDriverByName('SQLite')
srcdb = indriver.Open(“OUTDATA.sqlite”,0)
#create an output datasource in memory
outdriver=ogr.GetDriverByName('MEMORY')
source=outdriver.CreateDataSource('memData')
#open the memory datasource with write access
tmp=outdriver.Open('memData',1)
#copy a layer to memory
pipes_mem=source.CopyLayer(srcdb.GetLayer(‘pipes’),'pipes',['OVERWRITE=YES'])
#the new layer can be directly accessed via pipes_mem or as source.GetLayer(‘pipes’)
layer= source.GetLayer(‘pipes’)
for feature in layer:
	feature.SetField(‘SOMETHING’,1)

**Comment by pcjericks** [comment]
Nice!  Could you submit a pull request?

**Comment by pcjericks** [comment]
Thank you for the pull request.  Your recipe is now live:

http://pcjericks.github.io/py-gdalogr-cookbook/vector_layers.html#load-data-to-memory

Jared

**Comment by RolandLoewe** [comment]
yeah :)
