### ISSUE TITLE
Typo in Raster Layers  - get raster band information

### ISSUE THREAD

**Issue by Geogem** [pcjericks/py-gdalogr-cookbook#165]
Line 14 should be
`print 'Unable to open %s' % input_file`
but is
`print 'Unable to open %s' % src_filename`
. src_filename is not defined in this scope.

**Comment by pcjericks** [comment]
Can you put together a pull request?

Thanks!
Jared

**Comment by pcjericks** [comment]
Merged and published!  Thanks!
